# Generated by Django 3.2.8 on 2021-11-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0008_rename_rsa_administrative_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="eligibilitydiagnosis",
            name="historization_admin",
            field=models.TextField(blank=True, verbose_name="Commentaires des admins"),
        ),
    ]
