# Generated by Django 3.2.8 on 2021-11-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0037_auto_20210921_1614"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="historization_admin",
            field=models.TextField(blank=True, verbose_name="Commentaires des admins"),
        ),
    ]
