# Generated by Django 3.2.8 on 2021-11-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0019_alter_suspension_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="approval",
            name="historization_admin",
            field=models.TextField(blank=True, verbose_name="Commentaires des admins"),
        ),
        migrations.AddField(
            model_name="poleemploiapproval",
            name="historization_admin",
            field=models.TextField(blank=True, verbose_name="Commentaires des admins"),
        ),
        migrations.AddField(
            model_name="prolongation",
            name="historization_admin",
            field=models.TextField(blank=True, verbose_name="Commentaires des admins"),
        ),
        migrations.AddField(
            model_name="suspension",
            name="historization_admin",
            field=models.TextField(blank=True, verbose_name="Commentaires des admins"),
        ),
    ]
