# Generated by Django 3.2.8 on 2021-11-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_user_nir"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="historization_admin",
            field=models.TextField(blank=True, verbose_name="Commentaires des admins"),
        ),
    ]
